"""initial

Revision ID: d4be925c915c
Revises: 
Create Date: 2026-02-09 09:23:53.919935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4be925c915c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('title_original', sa.Text(), nullable=True),
    sa.Column('title_ja', sa.Text(), nullable=True),
    sa.Column('body_original', sa.Text(), nullable=True),
    sa.Column('body_translated', sa.Text(), nullable=True),
    sa.Column('summary_ja', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('og_image_url', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_table('digests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('article_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest_date')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('rss_url', sa.Text(), nullable=False),
    sa.Column('site_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rss_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_table('digests')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
