/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database connectivity */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch a URL and extract the article as Markdown (no storage) */
        post: operations["postIngest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-Sent Events: a `new_article` event per stored article, `ping` on connect */
        get: operations["getArticlesStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether an article URL is already stored */
        get: operations["getArticlesCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List articles, newest first (summaries only) */
        get: operations["getArticles"];
        put?: never;
        /** Store a processed article */
        post: operations["postArticles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_id}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Previous and next article by published date */
        get: operations["getArticlesByArticleIdNeighbors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Article detail including original and translated bodies */
        get: operations["getArticlesByArticleId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List digests, newest first */
        get: operations["getDigest"];
        put?: never;
        /** Store a daily digest */
        post: operations["postDigest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/source-articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full article bodies created on one JST day (defaults to yesterday) */
        get: operations["getDigestSourceArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/{digest_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Digest for a date (YYYY-MM-DD) */
        get: operations["getDigestByDigestDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List RSS sources */
        get: operations["getSources"];
        put?: never;
        /** Create an RSS source */
        post: operations["postSources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a source (partial; null clears a nullable field) */
        put: operations["putSourcesBySourceId"];
        post?: never;
        /** Deactivate a source (soft delete) */
        delete: operations["deleteSourcesBySourceId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed/rss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** RSS 2.0 feed of the 20 newest articles */
        get: operations["getFeedRss"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "healthy" | "unhealthy";
                        /** @enum {string} */
                        db: "connected" | "disconnected";
                    };
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "healthy" | "unhealthy";
                        /** @enum {string} */
                        db: "connected" | "disconnected";
                    };
                };
            };
        };
    };
    postIngest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                };
            };
        };
        responses: {
            /** @description Extracted article */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title: string | null;
                        body: string | null;
                        author: string | null;
                        published_at: string | null;
                        og_image_url: string | null;
                    };
                };
            };
            /** @description URL points to a private or reserved address */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description Fetch or extraction failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    getArticlesStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Too many SSE connections */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    getArticlesCheck: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Existence flag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        exists: boolean;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
        };
    };
    getArticles: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                date?: string;
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: uuid */
                            id: string;
                            source_url: string;
                            source_name: string | null;
                            title_ja: string | null;
                            summary_ja: string | null;
                            author: string | null;
                            /** Format: date-time */
                            published_at: string | null;
                            og_image_url: string | null;
                            categories: string[] | null;
                            /** Format: date-time */
                            created_at: string;
                        }[];
                        total: number;
                        page: number;
                        per_page: number;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
        };
    };
    postArticles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    source_url: string;
                    source_name?: string | null;
                    title_original?: string | null;
                    title_ja?: string | null;
                    body_original?: string | null;
                    body_translated?: string | null;
                    summary_ja?: string | null;
                    author?: string | null;
                    /** Format: date-time */
                    published_at?: string | null;
                    /** Format: uri */
                    og_image_url?: string | null;
                    categories?: string[] | null;
                    metadata?: {
                        [key: string]: unknown;
                    } | null;
                };
            };
        };
        responses: {
            /** @description Created article */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        source_url: string;
                        source_name: string | null;
                        title_ja: string | null;
                        summary_ja: string | null;
                        author: string | null;
                        /** Format: date-time */
                        published_at: string | null;
                        og_image_url: string | null;
                        categories: string[] | null;
                        /** Format: date-time */
                        created_at: string;
                        title_original: string | null;
                        body_original: string | null;
                        body_translated: string | null;
                        metadata: {
                            [key: string]: unknown;
                        } | null;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description An article with this source_url already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    getArticlesByArticleIdNeighbors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Neighbors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        prev: {
                            /** Format: uuid */
                            id: string;
                            title_ja: string | null;
                            og_image_url: string | null;
                            /** Format: date-time */
                            published_at: string | null;
                        } | null;
                        next: {
                            /** Format: uuid */
                            id: string;
                            title_ja: string | null;
                            og_image_url: string | null;
                            /** Format: date-time */
                            published_at: string | null;
                        } | null;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
            /** @description Article not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    getArticlesByArticleId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        source_url: string;
                        source_name: string | null;
                        title_ja: string | null;
                        summary_ja: string | null;
                        author: string | null;
                        /** Format: date-time */
                        published_at: string | null;
                        og_image_url: string | null;
                        categories: string[] | null;
                        /** Format: date-time */
                        created_at: string;
                        title_original: string | null;
                        body_original: string | null;
                        body_translated: string | null;
                        metadata: {
                            [key: string]: unknown;
                        } | null;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
            /** @description Article not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    getDigest: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated digests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: uuid */
                            id: string;
                            digest_date: string;
                            title: string | null;
                            article_count: number | null;
                            /** Format: date-time */
                            created_at: string;
                        }[];
                        total: number;
                        page: number;
                        per_page: number;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
        };
    };
    postDigest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    digest_date: string;
                    title?: string | null;
                    content?: string | null;
                    article_count?: number | null;
                    article_ids?: string[] | null;
                };
            };
        };
        responses: {
            /** @description Created digest */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        digest_date: string;
                        title: string | null;
                        article_count: number | null;
                        /** Format: date-time */
                        created_at: string;
                        content: string | null;
                        article_ids: string[] | null;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description A digest for this date already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    getDigestSourceArticles: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        date: string;
                        count: number;
                        truncated: boolean;
                        articles: {
                            /** Format: uuid */
                            id: string;
                            source_url: string;
                            source_name: string | null;
                            title_original: string | null;
                            title_ja: string | null;
                            summary_ja: string | null;
                            body_translated: string | null;
                            author: string | null;
                            /** Format: date-time */
                            published_at: string | null;
                            categories: string[] | null;
                            /** Format: date-time */
                            created_at: string;
                        }[];
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
        };
    };
    getDigestByDigestDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Digest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        digest_date: string;
                        title: string | null;
                        article_count: number | null;
                        /** Format: date-time */
                        created_at: string;
                        content: string | null;
                        article_ids: string[] | null;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
            /** @description Digest not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    getSources: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                active_only?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: uuid */
                            id: string;
                            name: string | null;
                            rss_url: string;
                            site_url: string | null;
                            category: string | null;
                            is_active: boolean;
                            /** Format: date-time */
                            created_at: string;
                        }[];
                        total: number;
                        page: number;
                        per_page: number;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
        };
    };
    postSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: uri */
                    rss_url: string;
                    /** Format: uri */
                    site_url?: string | null;
                    category?: string | null;
                };
            };
        };
        responses: {
            /** @description Created source */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string | null;
                        rss_url: string;
                        site_url: string | null;
                        category: string | null;
                        is_active: boolean;
                        /** Format: date-time */
                        created_at: string;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description A source with this rss_url already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    putSourcesBySourceId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string | null;
                    /** Format: uri */
                    rss_url?: string | null;
                    /** Format: uri */
                    site_url?: string | null;
                    category?: string | null;
                    is_active?: boolean | null;
                };
            };
        };
        responses: {
            /** @description Updated source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string | null;
                        rss_url: string;
                        site_url: string | null;
                        category: string | null;
                        is_active: boolean;
                        /** Format: date-time */
                        created_at: string;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description A source with this rss_url already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    deleteSourcesBySourceId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deactivated source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string | null;
                        rss_url: string;
                        site_url: string | null;
                        category: string | null;
                        is_active: boolean;
                        /** Format: date-time */
                        created_at: string;
                    };
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: Record<string, never>[];
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            /** @description Source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    getFeedRss: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RSS feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rss+xml": string;
                };
            };
            /** @description Feed generation failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string | {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
}
